// This small, dependency-free site only uses named local imports. Flatten those
// four sources into a classic script so direct file:// previews work in Chrome.
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { Script } from 'node:vm';

const root = new URL('../', import.meta.url);
const sources = ['fluid.mjs', 'fluid-shading.mjs', 'fluid-renderer.mjs', 'metaballs.js'];
const parts = sources.map(name => {
  let source = readFileSync(new URL(name, root), 'utf8');
  source = source.replace(/^import \{[^\n]+\} from '([^']+)';\r?\n/gm, (line, specifier) => {
    if (!specifier.startsWith('./') || !sources.includes(specifier.slice(2).split('?')[0])) {
      throw new Error(`Unsupported import in ${name}: ${specifier}`);
    }
    return '';
  }).replace(/^export (?=(?:class|function) )/gm, '');
  if (/^\s*(?:import|export)\s/m.test(source)) throw new Error(`Unsupported module syntax in ${name}`);
  return `// Source: ${name}\n${source.trim()}`;
});
const bundle = `// Generated by node scripts/build-site.mjs; edit the source modules instead.\n(() => {\n'use strict';\n${parts.join('\n\n')}\n})();\n`;
new Script(bundle, { filename: 'metaballs.bundle.js' });
const version = createHash('sha256').update(bundle).digest('hex').slice(0, 12);
const indexPath = new URL('index.html', root), html = readFileSync(indexPath, 'utf8');
const updated = html.replace(/src="metaballs\.bundle\.js\?v=[^"\s]+"/, `src="metaballs.bundle.js?v=${version}"`);
if (!updated.includes(`src="metaballs.bundle.js?v=${version}"`)) throw new Error('Bundle script missing from index.html');
const output = new URL('metaballs.bundle.js', root);
if (process.argv.includes('--check')) {
  if (readFileSync(output, 'utf8') !== bundle || html !== updated) {
    throw new Error('Site bundle is stale. Run node scripts/build-site.mjs');
  }
} else {
  writeFileSync(output, bundle);
  writeFileSync(indexPath, updated);
}
console.log(`Site bundle verified: ${bundle.length} bytes, ${version}`);
